name: devcalc
description: "A developer-focused calculator app for programmers. Offline, fast, and built with Flutter."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#0D1117"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

dependencies:
  equatable: ^2.0.8
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6

  # Navigation
  flutter_screenutil: ^5.9.3
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  get_it: ^9.2.1
  go_router: ^14.6.3
  google_fonts: ^6.3.2
  intl: ^0.20.2
  math_expressions: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.15.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
